name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-24.04' || matrix.os == 'ubuntu-24.04-arm'
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install dolphin # Install packages required by Dolphin
          sudo apt install libxi-dev
          sudo apt install libegl1-mesa-dev
          sudo apt install ffmpeg
          sudo apt install libudev-dev
          sudo apt install libevdev-dev
          sudo apt install build-essential
          sudo apt install cmake
          sudo apt install git
          sudo apt install libavcodec-dev
          sudo apt install libavformat-dev
          sudo apt install libcurl4-openssl-dev
          sudo apt install libdbus-1-dev
          sudo apt install libglew-dev
          sudo apt install libgtk-3-dev
          sudo apt install libopenal-dev
          sudo apt install libreadline-dev
          sudo apt install libxrandr-dev
          sudo apt install libxi-dev
          sudo apt install libxinerama-dev
          sudo apt install libx11-dev
          sudo apt install libasound2-dev
          sudo apt install libpulse-dev
          sudo apt install libfreetype6-dev
          sudo apt install libfontconfig1-dev
          sudo apt install libpng-dev
          sudo apt install libjpeg-dev
          sudo apt install libz-dev
          sudo apt install libxext-dev
          sudo apt install libxrender-dev
          sudo apt install libglu1-mesa-dev
          sudo apt install libgtkglext1-dev
          sudo apt install libgtest-dev
          sudo apt install libgmp-dev
          sudo apt install liblz4-dev
          sudo apt install liblzma-dev
          sudo apt install libsnappy-dev
          sudo apt install libtinyxml2-dev
          sudo apt install libxi-dev
          sudo apt install libxrandr-dev
          sudo apt install libxinerama-dev
          sudo apt install libx11-xcb-dev
          sudo apt install libxcb-glx0-dev
          sudo apt install libxcb1-dev
          sudo apt install libxcb-dri3-dev
          sudo apt install libxcb-dri2-0-dev
          sudo apt install libxcb-xfixes0-dev
          sudo apt install libxcb-randr0-dev
          sudo apt install libxcb-keysyms1-dev
          sudo apt install libxcb-image0-dev
          sudo apt install libxcb-shape0-dev
          sudo apt install libxcb-xinerama0-dev
          sudo apt install libxcb-util-dev
          sudo apt install libxcb-icccm4-dev
          sudo apt install libxcb-keysyms1-dev
          sudo apt install libxcb-xkb-dev
          sudo apt install libxkbcommon-dev
          sudo apt install libxkbcommon-x11-dev

      - uses: actions/setup-python@v5
        with:
          python-version: |
              3.11
              3.12
              3.13

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: 'auto64'
          CIBW_BUILD: cp311-* cp312-* cp313-*
          CIBW_MANYLINUX_X86_64_IMAGE: 'manylinux_2_28'
          CIBW_MANYLINUX_AARCH64_IMAGE: 'manylinux_2_28'
          CIBW_BEFORE_ALL_LINUX:  >
            dnf -y update && dnf -y upgrade && dnf groupinstall -y "Development Tools" && dnf install -y gcc gcc-c++ gcc-toolset-12 libxi-devel mesa-libEGL-devel ffmpeg systemd-devel libevdev-devel cmake git libavcodec-devel libavformat-devel libcurl-devel dbus-devel glew-devel gtk3-devel openal-soft-devel readline-devel libXrandr-devel libXinerama-devel libX11-devel alsa-lib-devel pulseaudio-libs-devel freetype-devel fontconfig-devel libpng-devel libjpeg-turbo-devel zlib-devel libXext-devel libXrender-devel mesa-libGLU-devel gtkglext-devel gtest-devel gmp-devel lz4-devel xz-devel snappy-devel tinyxml2-devel libX11-xcb-devel libxcb-glx-devel libxcb-devel libxcb-dri3-devel libxcb-dri2-devel libxcb-xfixes-devel libxcb-randr-devel libxcb-keysyms-devel libxcb-image-devel libxcb-shape-devel libxcb-xinerama-devel libxcb-util-devel libxcb-icccm-devel libxcb-keysyms-devel libxcb-xkb-devel libxkbcommon-devel libxkbcommon-x11-devel && scl enable gcc-toolset-12 bash



      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl