name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-24.04' || matrix.os == 'ubuntu-24.04-arm'
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install dolphin # Install packages required by Dolphin
          sudo apt install libxi-dev
          sudo apt install libegl1-mesa-dev
          sudo apt install ffmpeg
          sudo apt install libudev-dev
          sudo apt install libevdev-dev
          sudo apt install build-essential
          sudo apt install cmake
          sudo apt install git
          sudo apt install libavcodec-dev
          sudo apt install libavformat-dev
          sudo apt install libcurl4-openssl-dev
          sudo apt install libdbus-1-dev
          sudo apt install libglew-dev
          sudo apt install libgtk-3-dev
          sudo apt install libopenal-dev
          sudo apt install libreadline-dev
          sudo apt install libxrandr-dev
          sudo apt install libxi-dev
          sudo apt install libxinerama-dev
          sudo apt install libx11-dev
          sudo apt install libasound2-dev
          sudo apt install libpulse-dev
          sudo apt install libfreetype6-dev
          sudo apt install libfontconfig1-dev
          sudo apt install libpng-dev
          sudo apt install libjpeg-dev
          sudo apt install libz-dev
          sudo apt install libxext-dev
          sudo apt install libxrender-dev
          sudo apt install libglu1-mesa-dev
          sudo apt install libgtkglext1-dev
          sudo apt install libgtest-dev
          sudo apt install libgmp-dev
          sudo apt install liblz4-dev
          sudo apt install liblzma-dev
          sudo apt install libsnappy-dev
          sudo apt install libtinyxml2-dev
          sudo apt install libxi-dev
          sudo apt install libxrandr-dev
          sudo apt install libxinerama-dev
          sudo apt install libx11-xcb-dev
          sudo apt install libxcb-glx0-dev
          sudo apt install libxcb1-dev
          sudo apt install libxcb-dri3-dev
          sudo apt install libxcb-dri2-0-dev
          sudo apt install libxcb-xfixes0-dev
          sudo apt install libxcb-randr0-dev
          sudo apt install libxcb-keysyms1-dev
          sudo apt install libxcb-image0-dev
          sudo apt install libxcb-shape0-dev
          sudo apt install libxcb-xinerama0-dev
          sudo apt install libxcb-util-dev
          sudo apt install libxcb-icccm4-dev
          sudo apt install libxcb-keysyms1-dev
          sudo apt install libxcb-xkb-dev
          sudo apt install libxkbcommon-dev
          sudo apt install libxkbcommon-x11-dev

      - uses: actions/setup-python@v5
        with:
          python-version: |
              3.11
              3.12
              3.13

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: 'auto64'
          CIBW_BUILD: cp311-* cp312-* cp313-*
          CIBW_MANYLINUX_X86_64_IMAGE: 'manylinux_2_28'
          CIBW_MANYLINUX_AARCH64_IMAGE: 'manylinux_2_28'
          CIBW_BEFORE_ALL_LINUX:  >
            dnf update && dnf upgrade && dnf install dolphin && dnf install libxi-devel && dnf install mesa-libEGL-devel && dnf install ffmpeg && dnf install systemd-devel && dnf install libevdev-devel && dnf groupinstall "Development Tools" && dnf install cmake && dnf install git && dnf install libavcodec-devel && dnf install libavformat-devel && dnf install libcurl-devel && dnf install dbus-devel && dnf install glew-devel && dnf install gtk3-devel && dnf install openal-soft-devel && dnf install readline-devel && dnf install libXrandr-devel && dnf install libxi-devel && dnf install libXinerama-devel && dnf install libX11-devel && dnf install alsa-lib-devel && dnf install pulseaudio-libs-devel && dnf install freetype-devel && dnf install fontconfig-devel && dnf install libpng-devel && dnf install libjpeg-turbo-devel && dnf install zlib-devel && dnf install libXext-devel && dnf install libXrender-devel && dnf install mesa-libGLU-devel && dnf install gtkglext-devel && dnf install gtest-devel && dnf install gmp-devel && dnf install lz4-devel && dnf install xz-devel && dnf install snappy-devel && dnf install tinyxml2-devel && dnf install libxi-devel && dnf install libXrandr-devel && dnf install libXinerama-devel && dnf install libX11-xcb-devel && dnf install libxcb-glx-devel && dnf install libxcb-devel && dnf install libxcb-dri3-devel && dnf install libxcb-dri2-devel && dnf install libxcb-xfixes-devel && dnf install libxcb-randr-devel && dnf install libxcb-keysyms-devel && dnf install libxcb-image-devel && dnf install libxcb-shape-devel && dnf install libxcb-xinerama-devel && dnf install libxcb-util-devel && dnf install libxcb-icccm-devel && dnf install libxcb-keysyms-devel && dnf install libxcb-xkb-devel && dnf install libxkbcommon-devel && dnf install libxkbcommon-x11-devel



      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl